// Наши онсновные скрипты темы /themes/index36/js/header.first.js
// DO NOT EDIT THIS FILE WITHOUT BACKUP !!!


/**
 * ============================================
 * themes/index36/js/header.first.js
 * Кнопка «Ещё» и мега-меню под шапкой
 * ============================================
 */

document.addEventListener('DOMContentLoaded', function () {
  // Кнопка-триггер
  const btn = document.getElementById('navMoreBtn');
  // Само мега-меню
  const menu = document.getElementById('megaMenu');

  // Если кнопки или меню нет — выходим
  if (!btn || !menu) return;

  // Открыть/закрыть панель
  function toggleMenu(force) {
    const isOpen = (typeof force === 'boolean') ? force : !menu.classList.contains('open');
    menu.classList.toggle('open', isOpen);
    btn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
  }

  // Клик по кнопке — переключаем состояние, не пробрасываем наверх
  btn.addEventListener('click', function (e) {
    e.stopPropagation();
    toggleMenu();
  });

  // Клик вне меню — закрываем
  document.addEventListener('click', function (e) {
    if (!menu.contains(e.target) && !btn.contains(e.target)) {
      toggleMenu(false);
    }
  });

  // Escape — закрываем
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') toggleMenu(false);
  });

  // Клик по ссылке внутри меню — закрываем (перед переходом)
  menu.addEventListener('click', function (e) {
    if (e.target.closest('a')) toggleMenu(false);
  });
});
