// DO NOT EDIT THIS FILE WITHOUT BACKUP !!!

function toggleTheme() {
  const html = document.documentElement;
  const current = html.getAttribute('data-bs-theme') || 'light';
  const next = current === 'light' ? 'dark' : 'light';
  html.setAttribute('data-bs-theme', next);
  localStorage.setItem('theme', next);
  const icon = document.querySelector('.theme-icon');
  if (icon) icon.className = 'theme-icon fa-solid ' + (next === 'light' ? 'fa-moon' : 'fa-sun');
}
document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('theme');
  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
  const theme = saved || (prefersDark ? 'dark' : 'light');
  document.documentElement.setAttribute('data-bs-theme', theme);
  const icon = document.querySelector('.theme-icon');
  if (icon) icon.className = 'theme-icon fa-solid ' + (theme === 'light' ? 'fa-moon' : 'fa-sun');
});
	

$(document).ready(function() {
    const body = document.body;
    const TAB_KEY = 'last-active-sidebar-tab';
    const STATE_KEY = 'sidebar-desktop-state';

    function restoreActiveTab() {
        const saved = localStorage.getItem(TAB_KEY) || 'pages';
        document.querySelectorAll('.sidebar-tab').forEach(el => {
            el.classList.remove('active');
            if (el.dataset.tab === saved) el.classList.add('active');
        });
        document.querySelectorAll('.panel-content').forEach(p => p.classList.add('d-none'));
        const panel = document.getElementById('panel-' + saved);
        if (panel) panel.classList.remove('d-none');
    }

    function applyResponsiveState() {
        if (window.innerWidth >= 992) {
            body.classList.remove('mobile-open');
            let state = localStorage.getItem(STATE_KEY) || 'closed';
            if (state === 'open') {
                body.classList.add('sidebar-open');
                body.classList.remove('sidebar-closed');
            } else {
                body.classList.add('sidebar-closed');
                body.classList.remove('sidebar-open');
            }
        } else {
            body.classList.remove('sidebar-open', 'sidebar-closed');
        }
    }

    // Делегирование клика для корректной работы на мобильных после авторизации
    $(document).on('click', '#panelToggle', function(e) {
        e.preventDefault();
        if (window.innerWidth < 992) {
            body.classList.toggle('mobile-open');
            return;
        }
        body.classList.toggle('sidebar-open');
        body.classList.toggle('sidebar-closed');
        const isOpen = body.classList.contains('sidebar-open');
        localStorage.setItem(STATE_KEY, isOpen ? 'open' : 'closed');
    });

    document.querySelectorAll('.sidebar-tab').forEach(tab => {
        tab.addEventListener('click', function(e) {
            e.preventDefault();
            document.querySelectorAll('.sidebar-tab').forEach(t => t.classList.remove('active'));
            this.classList.add('active');
            document.querySelectorAll('.panel-content').forEach(p => p.classList.add('d-none'));
            const panel = document.getElementById('panel-' + this.dataset.tab);
            if (panel) {
                panel.classList.remove('d-none');
                if (window.innerWidth >= 992) {
                    if (!body.classList.contains('sidebar-open')) {
                        body.classList.add('sidebar-open');
                        body.classList.remove('sidebar-closed');
                        localStorage.setItem(STATE_KEY, 'open');
                    }
                } else {
                    body.classList.add('mobile-open');
                }
            }
            localStorage.setItem(TAB_KEY, this.dataset.tab);
        });
    });

    restoreActiveTab();
    applyResponsiveState();
    window.addEventListener('load', applyResponsiveState);
    window.addEventListener('resize', applyResponsiveState);
});
// === Sidebar toggle icon sync ===
document.addEventListener('DOMContentLoaded', function () {

    const body = document.body;
    const icon = document.querySelector('#panelToggle i');

    function updateSidebarIcon() {
        if (!icon) return;

        const isDesktopOpen = body.classList.contains('sidebar-open');
        const isMobileOpen  = body.classList.contains('mobile-open');
        const isOpen = isDesktopOpen || isMobileOpen;

        if (isOpen) {
            icon.className = 'fa-regular fa-square-caret-left fa-xl link-danger';
        } else {
            icon.className = 'fa-solid fa-bars fa-xl';
        }
    }

    // Обновление при клике на кнопку
    document.addEventListener('click', function (e) {
        if (e.target.closest('#panelToggle')) {
            // Ждём выполнения вашего основного toggle
            setTimeout(updateSidebarIcon, 0);
        }
    });

    // Обновление при загрузке и ресайзе
    updateSidebarIcon();
    window.addEventListener('resize', updateSidebarIcon);
});
